/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllotmentRouteImport } from './routes/allotment'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as IpoSlugRouteImport } from './routes/ipo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllotmentRoute = AllotmentRouteImport.update({
  id: '/allotment',
  path: '/allotment',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoSlugRoute = IpoSlugRouteImport.update({
  id: '/ipo/$slug',
  path: '/ipo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allotment': typeof AllotmentRoute
  '/books': typeof BooksRoute
  '/calendar': typeof CalendarRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/members': typeof MembersRoute
  '/tools': typeof ToolsRoute
  '/ipo/$slug': typeof IpoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allotment': typeof AllotmentRoute
  '/books': typeof BooksRoute
  '/calendar': typeof CalendarRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/members': typeof MembersRoute
  '/tools': typeof ToolsRoute
  '/ipo/$slug': typeof IpoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allotment': typeof AllotmentRoute
  '/books': typeof BooksRoute
  '/calendar': typeof CalendarRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/members': typeof MembersRoute
  '/tools': typeof ToolsRoute
  '/ipo/$slug': typeof IpoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allotment'
    | '/books'
    | '/calendar'
    | '/invest'
    | '/investments'
    | '/members'
    | '/tools'
    | '/ipo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allotment'
    | '/books'
    | '/calendar'
    | '/invest'
    | '/investments'
    | '/members'
    | '/tools'
    | '/ipo/$slug'
  id:
    | '__root__'
    | '/'
    | '/allotment'
    | '/books'
    | '/calendar'
    | '/invest'
    | '/investments'
    | '/members'
    | '/tools'
    | '/ipo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllotmentRoute: typeof AllotmentRoute
  BooksRoute: typeof BooksRoute
  CalendarRoute: typeof CalendarRoute
  InvestRoute: typeof InvestRoute
  InvestmentsRoute: typeof InvestmentsRoute
  MembersRoute: typeof MembersRoute
  ToolsRoute: typeof ToolsRoute
  IpoSlugRoute: typeof IpoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allotment': {
      id: '/allotment'
      path: '/allotment'
      fullPath: '/allotment'
      preLoaderRoute: typeof AllotmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo/$slug': {
      id: '/ipo/$slug'
      path: '/ipo/$slug'
      fullPath: '/ipo/$slug'
      preLoaderRoute: typeof IpoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllotmentRoute: AllotmentRoute,
  BooksRoute: BooksRoute,
  CalendarRoute: CalendarRoute,
  InvestRoute: InvestRoute,
  InvestmentsRoute: InvestmentsRoute,
  MembersRoute: MembersRoute,
  ToolsRoute: ToolsRoute,
  IpoSlugRoute: IpoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
