export type Board = "Mainboard" | "SME";
export type IpoStatus = "open" | "upcoming" | "closed" | "listed";

export type Subscription = {
  qib: number;
  nii: number;
  retail: number;
  emp?: number;
  total: number;
};

export type Financials = {
  fy: string;
  revenueCr: number;
  patCr: number;
};

export type Ipo = {
  slug: string;
  name: string;
  ticker: string;
  board: Board;
  exchanges: string;
  sector: string;
  status: IpoStatus;
  priceLow: number;
  priceHigh: number;
  lot: number;
  issueCr: number;
  freshCr: number;
  ofsCr: number;
  gmp: number;
  gmpHistory: number[];
  open: string;
  close: string;
  allotment: string;
  listing: string;
  registrar: string;
  subscription: Subscription;
  about: string;
  objects: string[];
  financials: Financials[];
  pe: number | null;
  rhp: string;
};

export const TODAY = "2026-09-16";

export const IPOS: Ipo[] = [
  {
    slug: "ss-retail",
    name: "SS Retail",
    ticker: "SSRETAIL",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Retail",
    status: "open",
    priceLow: 403,
    priceHigh: 424,
    lot: 35,
    issueCr: 500,
    freshCr: 360,
    ofsCr: 140,
    gmp: 105,
    gmpHistory: [72, 78, 86, 91, 98, 102, 105],
    open: "2026-09-16",
    close: "2026-09-18",
    allotment: "2026-09-19",
    listing: "2026-09-23",
    registrar: "KFin Technologies",
    subscription: { qib: 1.42, nii: 0.88, retail: 2.15, total: 1.61 },
    about:
      "Multi-format apparel and lifestyle retailer with a pan-India store network and growing private-label mix.",
    objects: [
      "Store expansion in tier-1 and tier-2 cities",
      "Working capital for inventory",
      "General corporate purposes",
    ],
    financials: [
      { fy: "FY24", revenueCr: 1840, patCr: 92 },
      { fy: "FY25", revenueCr: 2210, patCr: 118 },
      { fy: "FY26", revenueCr: 2680, patCr: 146 },
    ],
    pe: 28.4,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "jindal-supreme",
    name: "Jindal Supreme (India)",
    ticker: "JINDSPRM",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Capital goods",
    status: "open",
    priceLow: 88,
    priceHigh: 93,
    lot: 161,
    issueCr: 620,
    freshCr: 480,
    ofsCr: 140,
    gmp: 24,
    gmpHistory: [9, 11, 14, 16, 19, 22, 24],
    open: "2026-09-16",
    close: "2026-09-18",
    allotment: "2026-09-19",
    listing: "2026-09-23",
    registrar: "Link Intime",
    subscription: { qib: 2.08, nii: 1.34, retail: 3.62, total: 2.41 },
    about:
      "Manufacturer of precision tubes, structural steel, and engineered components serving infrastructure and auto OEMs.",
    objects: ["Capacity expansion at Palwal", "Debt repayment", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 980, patCr: 54 },
      { fy: "FY25", revenueCr: 1210, patCr: 71 },
      { fy: "FY26", revenueCr: 1490, patCr: 88 },
    ],
    pe: 22.1,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "hero-motors",
    name: "Hero Motors",
    ticker: "HEROMTR",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Auto components",
    status: "open",
    priceLow: 79,
    priceHigh: 84,
    lot: 178,
    issueCr: 740,
    freshCr: 540,
    ofsCr: 200,
    gmp: 11,
    gmpHistory: [18, 16, 15, 13, 12, 11, 11],
    open: "2026-09-16",
    close: "2026-09-18",
    allotment: "2026-09-19",
    listing: "2026-09-23",
    registrar: "MUFG Intime",
    subscription: { qib: 0.94, nii: 0.61, retail: 1.28, total: 0.97 },
    about:
      "Powertrain and e-mobility components supplier with exports into Europe and ASEAN.",
    objects: ["EV drivetrain capex", "R&D", "General corporate purposes"],
    financials: [
      { fy: "FY24", revenueCr: 1620, patCr: 78 },
      { fy: "FY25", revenueCr: 1880, patCr: 91 },
      { fy: "FY26", revenueCr: 2110, patCr: 102 },
    ],
    pe: 26.8,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "manika-plastech",
    name: "Manika Plastech",
    ticker: "MANIKA",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Plastics",
    status: "open",
    priceLow: 40,
    priceHigh: 43,
    lot: 348,
    issueCr: 186,
    freshCr: 186,
    ofsCr: 0,
    gmp: 5,
    gmpHistory: [2, 3, 4, 4, 5, 5, 5],
    open: "2026-09-11",
    close: "2026-09-16",
    allotment: "2026-09-17",
    listing: "2026-09-22",
    registrar: "Bigshare Services",
    subscription: { qib: 4.12, nii: 2.08, retail: 6.4, total: 4.55 },
    about:
      "Rigid packaging and industrial plastic solutions for FMCG, pharma, and chemicals.",
    objects: ["New extrusion lines", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 312, patCr: 18 },
      { fy: "FY25", revenueCr: 368, patCr: 24 },
      { fy: "FY26", revenueCr: 421, patCr: 29 },
    ],
    pe: 18.6,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "vama-wovenfab",
    name: "Vama Wovenfab",
    ticker: "VAMAWOV",
    board: "SME",
    exchanges: "BSE SME",
    sector: "Textiles",
    status: "open",
    priceLow: 324,
    priceHigh: 341,
    lot: 400,
    issueCr: 68.2,
    freshCr: 68.2,
    ofsCr: 0,
    gmp: 30,
    gmpHistory: [12, 16, 18, 22, 26, 28, 30],
    open: "2026-09-15",
    close: "2026-09-17",
    allotment: "2026-09-18",
    listing: "2026-09-22",
    registrar: "KFin Technologies",
    subscription: { qib: 0.42, nii: 0.21, retail: 0.68, total: 0.48 },
    about: "Technical woven fabrics and industrial textiles for packaging and geotextiles.",
    objects: ["Loom modernisation", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 94, patCr: 8.2 },
      { fy: "FY25", revenueCr: 118, patCr: 11.4 },
      { fy: "FY26", revenueCr: 141, patCr: 14.1 },
    ],
    pe: 21.2,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "shakti-polytarp",
    name: "Shakti Polytarp",
    ticker: "SHAKPOLY",
    board: "SME",
    exchanges: "BSE SME",
    sector: "Packaging",
    status: "open",
    priceLow: 56,
    priceHigh: 59,
    lot: 2000,
    issueCr: 42.4,
    freshCr: 42.4,
    ofsCr: 0,
    gmp: 0,
    gmpHistory: [0, 0, 1, 0, 0, 0, 0],
    open: "2026-09-15",
    close: "2026-09-17",
    allotment: "2026-09-18",
    listing: "2026-09-22",
    registrar: "Skyline Financial",
    subscription: { qib: 0.18, nii: 0.09, retail: 0.31, total: 0.22 },
    about: "HDPE tarpaulins and polymer sheets for agriculture and logistics.",
    objects: ["Capacity addition", "Debt repayment"],
    financials: [
      { fy: "FY24", revenueCr: 61, patCr: 4.1 },
      { fy: "FY25", revenueCr: 74, patCr: 5.2 },
      { fy: "FY26", revenueCr: 86, patCr: 6.0 },
    ],
    pe: 16.4,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "quanto-agroworld",
    name: "Quanto Agroworld",
    ticker: "QUANTO",
    board: "SME",
    exchanges: "BSE SME",
    sector: "Agri inputs",
    status: "open",
    priceLow: 67,
    priceHigh: 67,
    lot: 2000,
    issueCr: 38.9,
    freshCr: 38.9,
    ofsCr: 0,
    gmp: 0,
    gmpHistory: [2, 1, 0, 0, 0, 0, 0],
    open: "2026-09-15",
    close: "2026-09-17",
    allotment: "2026-09-18",
    listing: "2026-09-22",
    registrar: "Bigshare Services",
    subscription: { qib: 0.11, nii: 0.05, retail: 0.19, total: 0.13 },
    about: "Crop nutrition and micronutrient formulations for western and central India.",
    objects: ["Formulation plant", "Brand spend"],
    financials: [
      { fy: "FY24", revenueCr: 48, patCr: 3.2 },
      { fy: "FY25", revenueCr: 57, patCr: 4.0 },
      { fy: "FY26", revenueCr: 66, patCr: 4.6 },
    ],
    pe: 19.8,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "century-business-media",
    name: "Century Business Media",
    ticker: "CBMEDIA",
    board: "SME",
    exchanges: "BSE SME",
    sector: "Media",
    status: "open",
    priceLow: 70,
    priceHigh: 74,
    lot: 1600,
    issueCr: 51.6,
    freshCr: 51.6,
    ofsCr: 0,
    gmp: 8,
    gmpHistory: [4, 5, 6, 6, 7, 8, 8],
    open: "2026-09-11",
    close: "2026-09-16",
    allotment: "2026-09-17",
    listing: "2026-09-21",
    registrar: "Link Intime",
    subscription: { qib: 3.51, nii: 0.3, retail: 0.12, total: 1.06 },
    about: "B2B publishing, events, and digital media for industrial verticals.",
    objects: ["Digital product build", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 72, patCr: 9.1 },
      { fy: "FY25", revenueCr: 84, patCr: 11.2 },
      { fy: "FY26", revenueCr: 97, patCr: 13.4 },
    ],
    pe: 14.9,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "injecto-polymers",
    name: "Injecto Polymers",
    ticker: "INJPOLY",
    board: "SME",
    exchanges: "BSE SME",
    sector: "Chemicals",
    status: "open",
    priceLow: 98,
    priceHigh: 100,
    lot: 1200,
    issueCr: 44.8,
    freshCr: 44.8,
    ofsCr: 0,
    gmp: 0,
    gmpHistory: [6, 4, 2, 1, 0, 0, 0],
    open: "2026-09-11",
    close: "2026-09-16",
    allotment: "2026-09-17",
    listing: "2026-09-21",
    registrar: "KFin Technologies",
    subscription: { qib: 1.02, nii: 0.07, retail: 0.26, total: 0.28 },
    about: "Specialty polymer compounds for auto interiors and consumer durables.",
    objects: ["Compounding lines", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 81, patCr: 6.4 },
      { fy: "FY25", revenueCr: 96, patCr: 7.8 },
      { fy: "FY26", revenueCr: 109, patCr: 8.9 },
    ],
    pe: 17.3,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "nse",
    name: "National Stock Exchange of India",
    ticker: "NSE",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Exchanges",
    status: "upcoming",
    priceLow: 1700,
    priceHigh: 1785,
    lot: 8,
    issueCr: 22561.57,
    freshCr: 0,
    ofsCr: 22561.57,
    gmp: 155,
    gmpHistory: [210, 198, 180, 172, 165, 160, 155],
    open: "2026-09-17",
    close: "2026-09-21",
    allotment: "2026-09-22",
    listing: "2026-09-24",
    registrar: "KFin Technologies",
    subscription: { qib: 0, nii: 0, retail: 0, total: 0 },
    about:
      "India’s primary equity, F&O, and currency exchange. Offer for sale by existing shareholders; no fresh issue.",
    objects: ["Offer for sale by selling shareholders"],
    financials: [
      { fy: "FY24", revenueCr: 14780, patCr: 8020 },
      { fy: "FY25", revenueCr: 16440, patCr: 8910 },
      { fy: "FY26", revenueCr: 18210, patCr: 9740 },
    ],
    pe: 42.6,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "sonaselection",
    name: "Sonaselection India",
    ticker: "SONASEL",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Textiles",
    status: "upcoming",
    priceLow: 94,
    priceHigh: 99,
    lot: 150,
    issueCr: 141.57,
    freshCr: 141.57,
    ofsCr: 0,
    gmp: 8,
    gmpHistory: [0, 2, 4, 6, 7, 8, 8],
    open: "2026-09-17",
    close: "2026-09-21",
    allotment: "2026-09-22",
    listing: "2026-09-24",
    registrar: "Link Intime",
    subscription: { qib: 0, nii: 0, retail: 0, total: 0 },
    about: "Home textiles exporter with capacity in Rajasthan and a US/EU customer mix.",
    objects: ["Weaving capacity", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 286, patCr: 21 },
      { fy: "FY25", revenueCr: 332, patCr: 26 },
      { fy: "FY26", revenueCr: 378, patCr: 31 },
    ],
    pe: 19.4,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "spectraa-technology",
    name: "SpectraA Technology Solutions",
    ticker: "SPECTRAA",
    board: "SME",
    exchanges: "NSE SME",
    sector: "Capital goods",
    status: "upcoming",
    priceLow: 112,
    priceHigh: 118,
    lot: 1200,
    issueCr: 42.52,
    freshCr: 42.52,
    ofsCr: 0,
    gmp: 50,
    gmpHistory: [28, 32, 38, 42, 46, 48, 50],
    open: "2026-09-17",
    close: "2026-09-21",
    allotment: "2026-09-22",
    listing: "2026-09-24",
    registrar: "Bigshare Services",
    subscription: { qib: 0, nii: 0, retail: 0, total: 0 },
    about: "Industrial automation and test-equipment systems for electronics manufacturers.",
    objects: ["Facility expansion", "R&D"],
    financials: [
      { fy: "FY24", revenueCr: 38, patCr: 5.6 },
      { fy: "FY25", revenueCr: 49, patCr: 7.8 },
      { fy: "FY26", revenueCr: 61, patCr: 10.2 },
    ],
    pe: 16.8,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "kheria-autocomp",
    name: "Kheria Autocomp",
    ticker: "KHERIA",
    board: "SME",
    exchanges: "NSE SME",
    sector: "Auto components",
    status: "upcoming",
    priceLow: 96,
    priceHigh: 101,
    lot: 1200,
    issueCr: 46.44,
    freshCr: 46.44,
    ofsCr: 0,
    gmp: 10,
    gmpHistory: [4, 5, 6, 7, 8, 9, 10],
    open: "2026-09-17",
    close: "2026-09-21",
    allotment: "2026-09-22",
    listing: "2026-09-24",
    registrar: "Skyline Financial",
    subscription: { qib: 0, nii: 0, retail: 0, total: 0 },
    about: "Precision stamped and machined auto parts for two-wheeler and PV OEMs.",
    objects: ["Tool room", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 52, patCr: 4.8 },
      { fy: "FY25", revenueCr: 64, patCr: 6.1 },
      { fy: "FY26", revenueCr: 78, patCr: 7.4 },
    ],
    pe: 18.2,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "axiom-gas",
    name: "Axiom Gas Engineering",
    ticker: "AXIOMGAS",
    board: "SME",
    exchanges: "BSE SME",
    sector: "Oil & gas services",
    status: "upcoming",
    priceLow: 50,
    priceHigh: 53,
    lot: 2000,
    issueCr: 49.81,
    freshCr: 49.81,
    ofsCr: 0,
    gmp: 2,
    gmpHistory: [0, 0, 1, 1, 2, 2, 2],
    open: "2026-09-18",
    close: "2026-09-22",
    allotment: "2026-09-23",
    listing: "2026-09-25",
    registrar: "KFin Technologies",
    subscription: { qib: 0, nii: 0, retail: 0, total: 0 },
    about: "City-gas and industrial gas pipeline engineering contractor.",
    objects: ["Equipment", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 71, patCr: 5.1 },
      { fy: "FY25", revenueCr: 88, patCr: 6.6 },
      { fy: "FY26", revenueCr: 104, patCr: 7.9 },
    ],
    pe: 15.1,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "lcc-projects",
    name: "LCC Projects",
    ticker: "LCCPROJ",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Infrastructure",
    status: "listed",
    priceLow: 72,
    priceHigh: 78,
    lot: 192,
    issueCr: 540,
    freshCr: 400,
    ofsCr: 140,
    gmp: 22,
    gmpHistory: [18, 20, 21, 22, 24, 23, 22],
    open: "2026-09-08",
    close: "2026-09-10",
    allotment: "2026-09-12",
    listing: "2026-09-17",
    registrar: "Link Intime",
    subscription: { qib: 48.2, nii: 22.4, retail: 14.1, total: 26.8 },
    about: "EPC contractor for roads, water, and urban infrastructure.",
    objects: ["Working capital", "Equipment"],
    financials: [
      { fy: "FY24", revenueCr: 1240, patCr: 86 },
      { fy: "FY25", revenueCr: 1510, patCr: 109 },
      { fy: "FY26", revenueCr: 1780, patCr: 128 },
    ],
    pe: 16.2,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "rentomojo",
    name: "Rentomojo",
    ticker: "RENTO",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Consumer services",
    status: "listed",
    priceLow: 136,
    priceHigh: 148,
    lot: 101,
    issueCr: 820,
    freshCr: 520,
    ofsCr: 300,
    gmp: 38,
    gmpHistory: [42, 40, 39, 38, 38, 37, 38],
    open: "2026-09-08",
    close: "2026-09-10",
    allotment: "2026-09-12",
    listing: "2026-09-17",
    registrar: "KFin Technologies",
    subscription: { qib: 31.4, nii: 18.6, retail: 9.2, total: 18.7 },
    about: "Furniture, appliance, and gadget rental platform for urban India.",
    objects: ["Asset book growth", "Technology"],
    financials: [
      { fy: "FY24", revenueCr: 640, patCr: -42 },
      { fy: "FY25", revenueCr: 810, patCr: 12 },
      { fy: "FY26", revenueCr: 990, patCr: 48 },
    ],
    pe: 54.2,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "karamtara-engineering",
    name: "Karamtara Engineering",
    ticker: "KARAMTAR",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Engineering",
    status: "listed",
    priceLow: 236,
    priceHigh: 254,
    lot: 58,
    issueCr: 610,
    freshCr: 410,
    ofsCr: 200,
    gmp: 43,
    gmpHistory: [38, 40, 41, 42, 44, 43, 43],
    open: "2026-09-08",
    close: "2026-09-10",
    allotment: "2026-09-12",
    listing: "2026-09-17",
    registrar: "MUFG Intime",
    subscription: { qib: 22.1, nii: 11.4, retail: 6.8, total: 12.4 },
    about: "Transmission towers, poles, and heavy fabrication for power utilities.",
    objects: ["Plant expansion", "Debt repayment"],
    financials: [
      { fy: "FY24", revenueCr: 890, patCr: 64 },
      { fy: "FY25", revenueCr: 1040, patCr: 78 },
      { fy: "FY26", revenueCr: 1210, patCr: 94 },
    ],
    pe: 21.6,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "steamhouse-india",
    name: "Steamhouse India",
    ticker: "STEAMH",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Industrials",
    status: "listed",
    priceLow: 76,
    priceHigh: 81,
    lot: 185,
    issueCr: 390,
    freshCr: 390,
    ofsCr: 0,
    gmp: 16,
    gmpHistory: [12, 13, 14, 15, 16, 16, 16],
    open: "2026-09-08",
    close: "2026-09-10",
    allotment: "2026-09-12",
    listing: "2026-09-17",
    registrar: "Link Intime",
    subscription: { qib: 16.8, nii: 8.2, retail: 5.1, total: 9.4 },
    about: "Industrial boilers, heat recovery, and steam-system EPC.",
    objects: ["Manufacturing unit", "Working capital"],
    financials: [
      { fy: "FY24", revenueCr: 410, patCr: 32 },
      { fy: "FY25", revenueCr: 488, patCr: 41 },
      { fy: "FY26", revenueCr: 562, patCr: 49 },
    ],
    pe: 18.9,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "arcil",
    name: "Asset Reconstruction Company (India)",
    ticker: "ARCIL",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Financials",
    status: "listed",
    priceLow: 118,
    priceHigh: 125,
    lot: 120,
    issueCr: 2100,
    freshCr: 900,
    ofsCr: 1200,
    gmp: 9,
    gmpHistory: [14, 12, 11, 10, 9, 9, 9],
    open: "2026-09-08",
    close: "2026-09-10",
    allotment: "2026-09-12",
    listing: "2026-09-17",
    registrar: "KFin Technologies",
    subscription: { qib: 8.4, nii: 3.1, retail: 1.9, total: 4.2 },
    about: "India’s largest ARC by AUM, resolving stressed assets for banks and NBFCs.",
    objects: ["Capital for acquisitions", "OFS by existing investors"],
    financials: [
      { fy: "FY24", revenueCr: 1860, patCr: 410 },
      { fy: "FY25", revenueCr: 2140, patCr: 468 },
      { fy: "FY26", revenueCr: 2390, patCr: 512 },
    ],
    pe: 24.1,
    rhp: "https://www.sebi.gov.in/",
  },
  {
    slug: "manipal-payment",
    name: "Manipal Payment & Identity Solutions",
    ticker: "MANIPAL",
    board: "Mainboard",
    exchanges: "NSE & BSE",
    sector: "Fintech",
    status: "listed",
    priceLow: 210,
    priceHigh: 226,
    lot: 66,
    issueCr: 980,
    freshCr: 620,
    ofsCr: 360,
    gmp: -10,
    gmpHistory: [8, 4, 1, -2, -6, -8, -10],
    open: "2026-09-08",
    close: "2026-09-10",
    allotment: "2026-09-12",
    listing: "2026-09-17",
    registrar: "MUFG Intime",
    subscription: { qib: 1.8, nii: 0.9, retail: 0.7, total: 1.1 },
    about: "Payments, identity, and credentialing solutions for campuses, transit, and enterprises.",
    objects: ["Product build", "Acquisitions", "OFS"],
    financials: [
      { fy: "FY24", revenueCr: 540, patCr: 28 },
      { fy: "FY25", revenueCr: 610, patCr: 22 },
      { fy: "FY26", revenueCr: 690, patCr: 19 },
    ],
    pe: 68.4,
    rhp: "https://www.sebi.gov.in/",
  },
];

export function minInvest(ipo: Ipo) {
  return ipo.priceHigh * ipo.lot;
}

export function expectedList(ipo: Ipo) {
  return ipo.priceHigh + ipo.gmp;
}

export function gmpPct(ipo: Ipo) {
  if (!ipo.priceHigh) return 0;
  return (ipo.gmp / ipo.priceHigh) * 100;
}

export function getIpo(slug: string) {
  return IPOS.find((i) => i.slug === slug);
}

export function byStatus(s: IpoStatus) {
  return IPOS.filter((i) => i.status === s);
}

export const REGISTRARS = [
  { name: "KFin Technologies", url: "https://ipostatus.kfintech.com/" },
  { name: "Link Intime / MUFG Intime", url: "https://linkintime.co.in/initial_offer/public-issues.html" },
  { name: "Bigshare Services", url: "https://ipo.bigshareonline.com/IPO_Status.html" },
  { name: "Skyline Financial", url: "https://www.skylinerta.com/ipo.php" },
] as const;
